#include "driver_clk.h"

/** \brief Configure clock parameters, configuration is in driver_clk.h
 *
 * \return Nothing
 *
 */
void CLK_Init(void)
{
  /**< Set flash wait states to maximum for 48 MHz operation */
  NVMCTRL->CTRLB.reg = NVMCTRL_CTRLB_RWS(2) | NVMCTRL_CTRLB_MANW;
  MCLK->CPUDIV.reg = MCLK_CPUDIV_CPUDIV(MCLK_CPUDIV_CPUDIV_DIV1_Val);

#if CONF_XOSC_CONFIG == 1
	OSCCTRL->XOSCCTRL.reg = OSCCTRL_XOSCCTRL_STARTUP(CONF_XOSC_STARTUP) | (0 << OSCCTRL_XOSCCTRL_AMPGC_Pos)
	        | OSCCTRL_XOSCCTRL_GAIN(CONF_XOSC_GAIN) | (CONF_XOSC_RUNSTDBY << OSCCTRL_XOSCCTRL_RUNSTDBY_Pos)
	        | (CONF_XOSC_SWBEN << OSCCTRL_XOSCCTRL_SWBEN_Pos) | (CONF_XOSC_CFDEN << OSCCTRL_XOSCCTRL_CFDEN_Pos)
	        | (CONF_XOSC_XTALEN << OSCCTRL_XOSCCTRL_XTALEN_Pos) | (CONF_XOSC_ENABLE << OSCCTRL_XOSCCTRL_ENABLE_Pos);
#endif
#if CONF_OSC48M_CONFIG == 1
	OSCCTRL->OSC48MCTRL.reg = (CONF_OSC48M_RUNSTDBY << OSCCTRL_OSC48MCTRL_RUNSTDBY_Pos)
	                          | (CONF_OSC48M_ENABLE << OSCCTRL_OSC48MCTRL_ENABLE_Pos);
	OSCCTRL->OSC48MDIV.reg = OSCCTRL_OSC48MDIV_DIV(CONF_OSC48M_DIV);
	OSCCTRL->OSC48MSTUP.reg = OSCCTRL_OSC48MSTUP_STARTUP(CONF_OSC48M_STARTUP);
  while (OSCCTRL->OSC48MSYNCBUSY.reg);
#endif

#if CONF_XOSC_CONFIG == 1
#if CONF_XOSC_ENABLE == 1
	while (!OSCCTRL->STATUS.bit.XOSCRDY);
#endif
#if CONF_XOSC_AMPGC == 1
	OSCCTRL->XOSCCTRL.bit.AMPGC = 1;
#endif
#if CONF_XOSC_ONDEMAND == 1
	OSCCTRL->XOSCCTRL.bit.ONDEMAND = 1;
#endif
#endif

#if CONF_OSC48M_CONFIG == 1
#if CONF_OSC48M_ENABLE == 1
	while (!OSCCTRL->STATUS.bit.OSC48MRDY);
#endif
#if CONF_OSC48M_ONDEMAND == 1
	OSCCTRL->OSC48MCTRL.bit.ONDEMAND = 1;
#endif
#endif

#if CONF_XOSC_CONFIG == 1
#if CONF_DPLL_CONFIG == 1
  // enable GCLK1 as source for DPLL, divider = 16, output frequency = 1 MHz
	GCLK->GENCTRL[1].reg = GCLK_GENCTRL_DIV(16) | (1 << GCLK_GENCTRL_GENEN_Pos) | GCLK_GENCTRL_SRC_XOSC;
	while (GCLK->SYNCBUSY.reg & GCLK_SYNCBUSY_MASK);
#endif
#endif

#if CONF_DPLL_CONFIG == 1
#if CONF_DPLL_REFCLK == 2
	GCLK->PCHCTRL[0].reg = (1 << GCLK_PCHCTRL_CHEN_Pos) | GCLK_PCHCTRL_GEN(CONF_DPLL_GCLK);
#endif
  // enable DPLL to get 48 MHz as main frequency
	OSCCTRL->DPLLRATIO.reg = OSCCTRL_DPLLRATIO_LDRFRAC(CONF_DPLL_LDRFRAC) | OSCCTRL_DPLLRATIO_LDR(CONF_DPLL_LDR);
	OSCCTRL->DPLLCTRLB.reg = OSCCTRL_DPLLCTRLB_DIV(CONF_DPLL_DIV) | (CONF_DPLL_LBYPASS << OSCCTRL_DPLLCTRLB_LBYPASS_Pos)
	        | OSCCTRL_DPLLCTRLB_LTIME(CONF_DPLL_LTIME) | OSCCTRL_DPLLCTRLB_REFCLK(CONF_DPLL_REFCLK)
	        | (CONF_DPLL_WUF << OSCCTRL_DPLLCTRLB_WUF_Pos) | (CONF_DPLL_LPEN << OSCCTRL_DPLLCTRLB_LPEN_Pos)
	        | OSCCTRL_DPLLCTRLB_FILTER(CONF_DPLL_FILTER);
	OSCCTRL->DPLLPRESC.reg = OSCCTRL_DPLLPRESC_PRESC(CONF_DPLL_PRESC);
	OSCCTRL->DPLLCTRLA.reg = (CONF_DPLL_RUNSTDBY << OSCCTRL_DPLLCTRLA_RUNSTDBY_Pos)
                           | (CONF_DPLL_ENABLE << OSCCTRL_DPLLCTRLA_ENABLE_Pos);
#endif

#if CONF_DPLL_CONFIG == 1
#if CONF_DPLL_ENABLE == 1
	while (!(OSCCTRL->DPLLSTATUS.bit.LOCK || OSCCTRL->DPLLSTATUS.bit.CLKRDY));
#endif
#if CONF_DPLL_ONDEMAND == 1
	OSCCTRL->DPLLCTRLA.bit.ONDEMAND = 1;
#endif
#endif

#if CONF_OSC48M_CONFIG == 1
  /**< enable GCLK0 as main clock for the whole system */
	GCLK->GENCTRL[0].reg = GCLK_GENCTRL_DIV(1) | (1 << GCLK_GENCTRL_GENEN_Pos) | GCLK_GENCTRL_SRC_OSC48M;
	while (GCLK->SYNCBUSY.reg & GCLK_SYNCBUSY_MASK);
#endif
#if CONF_XOSC_CONFIG == 1
  /**< External oscillator is used as high-precision frequency source */
  GCLK->GENCTRL[2].reg = GCLK_GENCTRL_DIV(1) | (1 << GCLK_GENCTRL_GENEN_Pos) | GCLK_GENCTRL_SRC_XOSC;
	while (GCLK->SYNCBUSY.reg & GCLK_SYNCBUSY_MASK);
#endif
}
