# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyvisio.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets
from pubsub import pub


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 320)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(640, 320))
        MainWindow.setMaximumSize(QtCore.QSize(640, 320))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 641, 281))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(4, 0, 4, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbPosition = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.gbPosition.setEnabled(False)
        self.gbPosition.setObjectName("gbPosition")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.gbPosition)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(9, 10, 301, 81))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnLeft = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnLeft.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnLeft.setBaseSize(QtCore.QSize(50, 0))
        self.btnLeft.setObjectName("btnLeft")
        self.horizontalLayout_5.addWidget(self.btnLeft)
        self.sldPosition = QtWidgets.QSlider(self.verticalLayoutWidget_2)
        self.sldPosition.setOrientation(QtCore.Qt.Horizontal)
        self.sldPosition.setObjectName("sldPosition")
        self.horizontalLayout_5.addWidget(self.sldPosition)
        self.btnRight = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.btnRight.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnRight.setObjectName("btnRight")
        self.horizontalLayout_5.addWidget(self.btnRight)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(140, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.edPosition = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.edPosition.setMaximumSize(QtCore.QSize(50, 16777215))
        self.edPosition.setReadOnly(True)
        self.edPosition.setObjectName("edPosition")
        self.horizontalLayout_3.addWidget(self.edPosition)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.gbPosition)
        self.gbMeasurement = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.gbMeasurement.setEnabled(False)
        self.gbMeasurement.setMaximumSize(QtCore.QSize(16777215, 80))
        self.gbMeasurement.setObjectName("gbMeasurement")
        self.layoutWidget = QtWidgets.QWidget(self.gbMeasurement)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 10, 301, 59))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblVoltage = QtWidgets.QLabel(self.layoutWidget)
        self.lblVoltage.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lblVoltage.setTextFormat(QtCore.Qt.PlainText)
        self.lblVoltage.setObjectName("lblVoltage")
        self.horizontalLayout_6.addWidget(self.lblVoltage)
        self.edVoltage = QtWidgets.QLineEdit(self.layoutWidget)
        self.edVoltage.setMaximumSize(QtCore.QSize(50, 16777215))
        self.edVoltage.setReadOnly(True)
        self.edVoltage.setObjectName("edVoltage")
        self.horizontalLayout_6.addWidget(self.edVoltage)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.lblCurrent = QtWidgets.QLabel(self.layoutWidget)
        self.lblCurrent.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lblCurrent.setObjectName("lblCurrent")
        self.horizontalLayout_6.addWidget(self.lblCurrent)
        self.edCurrent = QtWidgets.QLineEdit(self.layoutWidget)
        self.edCurrent.setMinimumSize(QtCore.QSize(50, 0))
        self.edCurrent.setMaximumSize(QtCore.QSize(50, 16777215))
        self.edCurrent.setReadOnly(True)
        self.edCurrent.setObjectName("edCurrent")
        self.horizontalLayout_6.addWidget(self.edCurrent)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.lblTemperature = QtWidgets.QLabel(self.layoutWidget)
        self.lblTemperature.setMaximumSize(QtCore.QSize(25, 16777215))
        self.lblTemperature.setObjectName("lblTemperature")
        self.horizontalLayout_6.addWidget(self.lblTemperature)
        self.edTemp = QtWidgets.QLineEdit(self.layoutWidget)
        self.edTemp.setMinimumSize(QtCore.QSize(50, 0))
        self.edTemp.setMaximumSize(QtCore.QSize(50, 16777215))
        self.edTemp.setReadOnly(True)
        self.edTemp.setObjectName("edTemp")
        self.horizontalLayout_6.addWidget(self.edTemp)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.btnMeasure = QtWidgets.QPushButton(self.layoutWidget)
        self.btnMeasure.setObjectName("btnMeasure")
        self.horizontalLayout_4.addWidget(self.btnMeasure)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addWidget(self.gbMeasurement)
        self.groupBox_3 = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_3.setBaseSize(QtCore.QSize(0, 50))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 10, 311, 55))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(5, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbPorts = QtWidgets.QComboBox(self.layoutWidget1)
        self.cbPorts.setObjectName("cbPorts")
        self.horizontalLayout_2.addWidget(self.cbPorts)
        self.btnConnect = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnConnect.setMinimumSize(QtCore.QSize(50, 0))
        self.btnConnect.setObjectName("btnConnect")
        self.horizontalLayout_2.addWidget(self.btnConnect)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.btnPower = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnPower.setEnabled(False)
        self.btnPower.setMinimumSize(QtCore.QSize(60, 0))
        self.btnPower.setObjectName("btnPower")
        self.horizontalLayout_2.addWidget(self.btnPower)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.cbServo = QtWidgets.QComboBox(self.layoutWidget1)
        self.cbServo.setEnabled(False)
        self.cbServo.setMinimumSize(QtCore.QSize(200, 0))
        self.cbServo.setObjectName("cbServo")
        self.horizontalLayout_10.addWidget(self.cbServo)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gbParameters = QtWidgets.QGroupBox(self.horizontalLayoutWidget)
        self.gbParameters.setEnabled(False)
        self.gbParameters.setObjectName("gbParameters")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.gbParameters)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 19, 301, 251))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget_3)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 297, 216))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.scrollLayout = QtWidgets.QVBoxLayout(self.scrollArea)
        self.scrollArea.setWidget(self.scrollLayout.widget())
        
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.btnReadParams = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnReadParams.setObjectName("btnReadParams")
        self.horizontalLayout_7.addWidget(self.btnReadParams)
        self.btnWriteParams = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnWriteParams.setObjectName("btnWriteParams")
        self.horizontalLayout_7.addWidget(self.btnWriteParams)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout.addWidget(self.gbParameters)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "pyVisio"))
        self.gbPosition.setTitle(_translate("MainWindow", "Position"))
        self.btnLeft.setText(_translate("MainWindow", "Min"))
        self.btnRight.setText(_translate("MainWindow", "Max"))
        self.label_2.setText(_translate("MainWindow", "Readout"))
        self.gbMeasurement.setTitle(_translate("MainWindow", "Measurement"))
        self.lblVoltage.setText(_translate("MainWindow", "U"))
        self.lblCurrent.setText(_translate("MainWindow", "I"))
        self.lblTemperature.setText(_translate("MainWindow", "Temp"))
        self.btnMeasure.setText(_translate("MainWindow", "Read"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Connection"))
        self.btnConnect.setText(_translate("MainWindow", "Connect"))
        self.btnPower.setText(_translate("MainWindow", "Power On"))
        self.gbParameters.setTitle(_translate("MainWindow", "Parameters"))
        self.btnReadParams.setText(_translate("MainWindow", "Read"))
        self.btnWriteParams.setText(_translate("MainWindow", "Write"))
        
        self.btnConnect.clicked.connect(self.do_connect)
        self.btnLeft.clicked.connect(self.do_min)
        self.btnRight.clicked.connect(self.do_max)
        self.btnPower.clicked.connect(self.do_power)
        self.cbPorts.currentIndexChanged.connect(self.select_port)
        self.sldPosition.valueChanged.connect(self.change_pos)
        self.cbServo.currentIndexChanged.connect(self.select_servo)
        self.btnMeasure.clicked.connect(self.do_measure)
        
        pub.subscribe(self.done_connection, 'connected')
        pub.subscribe(self.done_disconnection, 'disconnected')
        pub.subscribe(self.conn_error, 'conn_error')
        pub.subscribe(self.get_measure, 'measure')
        pub.subscribe(self.show_pos, 'show_pos')
        pub.subscribe(self.add_param, 'add_param')
        pub.subscribe(self.remove_params, 'remove_params')
        self.connected = False
        self.powered = False
        self.measured = False
        
    def show_msg(self, title, text):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle(title)
        msg.setText(text)
        msg.setIcon(QtWidgets.QMessageBox.Critical)
        x = msg.exec_()

    def do_connect(self):
        if self.connected:
            pub.sendMessage("do_disconnect")
        else:
            self.btnConnect.setEnabled(False)
            self.cbPorts.setEnabled(False)
            self.gbMeasurement.setEnabled(False)
            self.gbParameters.setEnabled(False)
            self.gbPosition.setEnabled(False)
            self.btnPower.setEnabled(False)
            pub.sendMessage("do_connect", port=self.cbPorts.currentText())
        
    def conn_error(self):
        self.btnConnect.setEnabled(True)
        self.cbPorts.setEnabled(True)
        self.show_msg("Connection", "Port is not available!")

    def done_connection(self):
        self.btnConnect.setText("Disconnect")
        self.btnConnect.setStyleSheet("background-color: green")
        self.connected = True
        self.btnConnect.setEnabled(True)
        self.btnPower.setEnabled(True)
        self.gbMeasurement.setEnabled(True)
        self.gbParameters.setEnabled(True)
        self.gbPosition.setEnabled(True)   
        self.cbServo.setEnabled(True)   
        
    def done_disconnection(self):
        self.btnMeasure.setText("Read")
        self.cbPorts.setEnabled(True)
        self.btnConnect.setText("Connect")
        self.btnConnect.setStyleSheet("background-color: red")
        self.connected = False   
        
    def select_port(self):
        print(self.cbPorts.currentText())
        
    def select_servo(self):
        pub.sendMessage("select_servo", servo=self.cbServo.currentText())
        
    def add_port(self, port):
        self.cbPorts.addItem(port)
    
    def add_servo(self, name):
        self.cbServo.addItem(name)
        
    def change_pos(self):
        self.position = self.sldPosition.value()
        self.doubleSpinBox.setValue(self.position)
        pub.sendMessage("position_changing", position=self.position)
        
    def do_measure(self):
        if self.measured:
            self.measured = False
            pub.sendMessage("stop_measure")
            self.btnMeasure.setText("Read")
        else:
            self.measured = True
            pub.sendMessage("start_measure")
            self.btnMeasure.setText("Stop")
        
    def do_min(self):
        self.sldPosition.setValue(self.sldPosition.minimum())
    
    def do_max(self):
        self.sldPosition.setValue(self.sldPosition.maximum())
        
    def set_minmax(self, v_min, v_max):
        self.sldPosition.setMinimum(v_min)
        self.sldPosition.setMaximum(v_max)
        self.sldPosition.setValue(0)
        self.doubleSpinBox.setRange(v_min, v_max)
        
    def do_power(self):
        if self.powered:
            pub.sendMessage("power_off")
            self.btnPower.setText("Power On")
            self.powered = False
        else:
            pub.sendMessage("power_on")
            self.btnPower.setText("Power Off")
            self.change_pos()
            self.powered = True
            
    def get_measure(self, data):
        self.edVoltage.setText(data["U"])
        self.edCurrent.setText(data["I"])
        self.edTemp.setText(data["T"])
        
    def show_pos(self, pos):
        self.edPosition.setText(pos)
     
    def clearLayout(self, layout): 
        while layout.count(): 
            child = layout.takeAt(0) 
            if child.widget() is not None: 
                child.widget().deleteLater() 
            elif child.layout() is not None: 
                self.clearLayout(child.layout())

    def remove_params(self):
        self.clearLayout(self.scrollLayout)
        
    def add_param(self, name, param):
        param_layout = QtWidgets.QHBoxLayout()
        label_x = QtWidgets.QLabel()
        label_x.setText(name)
        label_x.setFixedHeight(30)
        param_layout.addWidget(label_x)
        param_layout.addStretch()
        #param_layout.addWidget(self._pause)
        self.SpinBox = QtWidgets.QSpinBox()
        self.SpinBox.setFixedHeight(30)
        param_layout.addWidget(self.SpinBox)
        self.SpinBox.setRange(param["min"], param["max"])
        self.SpinBox.setValue(param["dflt"])
        self.scrollLayout.addLayout(param_layout)
